image: maven:latest

variables:
  GIT_DEPTH: 0
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  GIT_DEPTH: "0"  

stages:
  - maven-build
  - sonarqube-check
  
maven-build: 
  stage: maven-build
  script:
    - mvn clean install
    - 'mvn deploy -s ci_settings.xml'
  only:
    - main
  
sonarqube-check:
  stage: sonarqube-check
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
    
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main
