image: maven:latest

variables:
  SONAR_TOKEN: "943693684bf0b7e178bf9fa3ad8c10c470ebaa9f"
  SONAR_HOST_URL: "http://sonarqube.lab.zivra.com:9000"
  GIT_DEPTH: 0

stages:
  - maven-build
  
maven-build: 
  stage: maven-build
  script:
    - mvn clean install
    - 'mvn deploy -s ci_settings.xml'
  only:
    - dev
  

