image: maven:latest

variables:
  GIT_DEPTH: 0
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  SSH_OPTIONS: "-o StrictHostKeyChecking=no"
  

stages:
  - maven-build
  - sonarqube-check
  - deploy
  
maven-build: 
  stage: maven-build
  script:
    - mvn clean install
    - 'mvn deploy -s ci_settings.xml'
    - 'curl -u admin:Zivra1234! -X POST "http://ec2-54-177-114-199.us-west-1.compute.amazonaws.com:8081/service/rest/v1/components?repository=DEMO-ARTIFACT" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "raw.directory=/latest" -F "raw.asset1=@./target/demo-0.0.1-SNAPSHOT.jar" -F "raw.asset1.filename=demo-0.0.1-SNAPSHOT.jar"'
  only:
    - main

sonarqube-check:
  stage: sonarqube-check
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
    
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main

autoDeploy:
  image: ubuntu
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && mkdir -p ~/.ssh && echo "$KNOWN_HOST" > ~/.ssh/known_hosts'
  script:
    - ssh $SSH_OPTIONS ec2-user@54.177.3.10 'echo "accessed"'
    - ssh ec2-user@54.177.3.10 'sudo systemctl stop web-demo'
    - ssh ec2-user@54.177.3.10 'wget http://ec2-54-177-114-199.us-west-1.compute.amazonaws.com:8081/repository/DEMO-ARTIFACT/latest/demo-0.0.1-SNAPSHOT.jar'
    - ssh ec2-user@54.177.3.10 'sudo mv ./demo-0.0.1-SNAPSHOT.jar /opt/web-demo.jar'
    - ssh ec2-user@54.177.3.10 'sudo systemctl start web-demo'
  only:
    - main
