image: maven:latest

variables:
  SONAR_TOKEN: "943693684bf0b7e178bf9fa3ad8c10c470ebaa9f"
  SONAR_HOST_URL: "http://sonarqube.lab.zivra.com:9000"
  GIT_DEPTH: 0

stages:
  - maven-build
  - sonarqube-check
  
maven-build: 
  stage: maven-build
  script:
    - mvn clean install
  

sonarqube-check:
  stage: sonarqube-check
  script:
    # - mvn verify sonar:sonar -e -X -Dsonar.qualitygate.wait=true
    - echo "Prueba"
  allow_failure: true
  

