image: maven:latest

variables:
  SONAR_TOKEN: "943693684bf0b7e178bf9fa3ad8c10c470ebaa9f"
  SONAR_HOST_URL: "http://sonarqube.lab.zivra.com:9000"
  GIT_DEPTH: 0

stages:
  - maven-build
  - sonarqube-check
  
maven-build: 
  stage: maven-build
  script:
    - mvn clean install
  only:
    - dev

sonarqube-check:
  stage: sonarqube-check
  script:
    - mvn sonar:sonar -Dsonar.projectKey=demo_logo -Dsonar.host.url=http://sonarqube.lab.zivra.com:9000 -Dsonar.login=943693684bf0b7e178bf9fa3ad8c10c470ebaa9f -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main

