name: 'Increment Tag'
description: 'Incrementa el ultimo tag'
outputs:
  incremented_tag:
    description: 'El tag incrementado'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lista de branches
      shell: bash
      run: |
         git fetch --prune --tags
         lista=$(git branch -r)
         echo "Branches: $lista"
        
    - name: Run increment-tag script
      id: tag-incrementado
      shell: bash
      run: |
        TAG=$(git describe --abbrev=0 --tags)
        echo "{TAG}={$TAG}" >> $GITHUB_OUTPUT
        echo "El ultimo tag es: ${{steps.tag-incrementado.outputs.TAG}}"
        INCREMENTED_TAG=$(bash .github/actions/increment-tag/increment-tag.sh $TAG)
        #echo "::set-output name=incremented_tag::$INCREMENTED_TAG"
        echo "{INCREMENTED-TAG}={$INCREMENTED_TAG}" >> GITHUB_OUTPUT
