name: Increment Tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment Tag
        id: increment-tag
        uses: ./.github/actions/increment-tag

      - name: Show Incremented Tag
        run: echo "Incremented Tag:${{ steps.increment-tag.outputs.incremented_tag}}"
