# Este script es para verificar el incremento de version del tag
name: incrementa_tag

on:
  workflow_dispatch:

jobs:
  incrementa_tag:
   runs-on: ubuntu-latest
 
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Ejecuta la accion para incrementar el tag
        uses: ./.github/actions/increment-tag/action@v1    
